export const SummerData = [
    {
        key: '1',
        nam: 'Royal Khaddar',
        price: '1199',
        code: 'kd-129',
        link: require('../assets/kd-129.jpeg'),
        link1: require('../assets/kd-131.jpeg'),
        link2: require('../assets/kd-131.jpeg'),
        rating: '5',
    },
    {
        key: '2',
        nam: 'Elite Khaddar',
        price: '1299',
        code: 'kd-130',
        link: require('../assets/kd-130.jpeg'),
        link1: require('../assets/kd-131.jpeg'),
        link2: require('../assets/kd-131.jpeg'),
        rating: '3',
    },
    {
        key: '3',
        nam: 'Handy Khaddar',
        price: '1399',
        code: 'kd-131',
        link: require('../assets/kd-131.jpeg'),
        link1: require('../assets/kd-131.jpeg'),
        link2: require('../assets/kd-131.jpeg'),
        rating: '4',
    },
    {
        key: '4',
        nam: 'Pure Khaddar',
        price: '1499',
        code: 'kd-132',
        link: require('../assets/kd-132.jpeg'),
        link1: require('../assets/kd-131.jpeg'),
        link2: require('../assets/kd-131.jpeg'),
        rating: '2',
    },
    {
        key: '5',
        nam: 'Simple Khaddar',
        price: '1199',
        code: 'kd-133',
        link: require('../assets/kd-133.jpeg'),
        link1: require('../assets/kd-131.jpeg'),
        link2: require('../assets/kd-131.jpeg'),
        rating: '1',
    },
    {
        key: '6',
        nam: 'Khaddar',
        price: '2199',
        code: 'kd-133',
        link: require('../assets/kd-133.jpeg'),
        link1: require('../assets/kd-131.jpeg'),
        link2: require('../assets/kd-131.jpeg'),
        rating: '5',
    },
    {
        key: '7',
        nam: 'Simple Khaddar',
        price: '2099',
        code: 'kd-133',
        link: require('../assets/kd-133.jpeg'),
        link1: require('../assets/kd-133.jpeg'),
        link2: require('../assets/kd-133.jpeg'),
        rating: '5',
    },
]
