export const WinterData = [
    {
        key: '1',
        nam: 'Royal Khaddar',
        price: '1999',
        code: 'kd-123',
        link: require('../assets/khaddar.png'),
        link1: require('../assets/kd-131.jpeg'),
        link2: require('../assets/kd-131.jpeg'),
        rating: '5',
    },
    {
        key: '2',
        nam: 'Royal Khaddar',
        price: '1999',
        code: 'kd-124',
        link: require('../assets/kd-124.jpeg'),
        link1: require('../assets/kd-131.jpeg'),
        link2: require('../assets/kd-131.jpeg'),
        rating: '3',
    },
    {
        key: '3',
        nam: 'Royal Khaddar',
        price: '1999',
        code: 'kd-125',
        link: require('../assets/kd-125.jpeg'),
        link1: require('../assets/kd-131.jpeg'),
        link2: require('../assets/kd-131.jpeg'),
        rating: '4',
    },
    {
        key: '4',
        nam: 'Royal Khaddar',
        price: '1999',
        code: 'kd-126',
        link: require('../assets/kd-126.jpeg'),
        link1: require('../assets/kd-131.jpeg'),
        link2: require('../assets/kd-131.jpeg'),
        rating: '2',
    },
    {
        key: '5',
        nam: 'Royal Khaddar',
        price: '1999',
        code: 'kd-127',
        link: require('../assets/kd-127.jpeg'),
        link1: require('../assets/kd-131.jpeg'),
        link2: require('../assets/kd-131.jpeg'),
        rating: '1',
    },
    {
        key: '6',
        nam: 'Royal Khaddar',
        price: '1999',
        code: 'kd-128',
        link: require('../assets/kd-128.jpeg'),
        link1: require('../assets/kd-131.jpeg'),
        link2: require('../assets/kd-131.jpeg'),
        rating: '5',
    },
]
